name: build-check

on:
  pull_request:

jobs:
  server-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Install server Dependencies
        working-directory: ./server
        run: go mod download
      - name: server Build Check
        working-directory: ./server/cmd/server
        run: go build -o main .
